security:
    enable_authenticator_manager: true

    # Gestion des hashers pour les mots de passe
    password_hashers:
        App\Entity\Restaurants:
            algorithm: auto
        App\Entity\Clients:
            algorithm: auto

    # Configuration des fournisseurs d'utilisateurs
    providers:
        restaurants_provider:
            entity:
                class: App\Entity\Restaurants
                property: mail

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            provider: restaurants_provider
            form_login:
                login_path: app_login_restaurants
                check_path: app_login_restaurants
                username_parameter: mail
                password_parameter: mdp
                default_target_path: /plateforme  # Page par défaut après connexion
            logout:
                path: app_logout
                target: /
                invalidate_session: true

    # Règles de contrôle d'accès
    access_control:
        - { path: ^/restaurants/connexion, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/plateforme, roles: ROLE_RESTAURANT }
        - { path: ^/restaurants/inscription, roles: IS_AUTHENTICATED_ANONYMOUSLY }
