security:
    enable_authenticator_manager: true

    providers:
        app_user_provider:
            entity:
                class: App\Entity\Clients
                property: mail # Champ utilisé pour l'authentification

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            lazy: true
            provider: app_user_provider
            form_login:
                login_path: app_login_clients
                check_path: app_login_clients
                username_parameter: mail # Correspond au champ 'mail' dans ton formulaire
                password_parameter: mdp # Correspond au champ 'mdp' dans ton formulaire
            logout:
                path: /clients/deconnexion # Route de déconnexion pour les clients
                target: / # Redirection vers la page d'accueil (ou une autre page pour les clients)

        # Pour gérer la déconnexion des restaurants, tu peux configurer un autre firewall
        restaurant:
            provider: app_user_provider
            form_login:
                login_path: app_login_restaurants
                check_path: app_login_restaurants
                username_parameter: mail
                password_parameter: mdp
            logout:
                path: /restaurants/deconnexion # Route de déconnexion pour les restaurants
                target: / # Redirection vers la page d'accueil (ou autre page pour les restaurants)

    password_hashers:
        App\Entity\Clients: 
            algorithm: auto
